version: '3'

services:
  react:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./todo:/usr/src/todo
      - node_modules_volume:/usr/src/todo/node_modules
      - app_node_modules_volume:/usr/src/todo/todo-app/node_modules
    ports:
      - '3000:3000'
    tty: true

volumes:
  node_modules_volume:
  app_node_modules_volume:
    